-- 1: Create tables for Supplier and Product
CREATE TABLE SUPPLIER (
    SUPNR INT NOT NULL PRIMARY KEY,
    SUPNAME VARCHAR2(30) NOT NULL,
    SUPADDRESS VARCHAR2(50),
    SUPCITY VARCHAR2(30),
    SUPSTATUS VARCHAR2(10),
    SUPEMAIL VARCHAR2(20) UNIQUE
);

CREATE TABLE PRODUCT (
    PRODNR NUMBER(3) NOT NULL PRIMARY KEY,
    PRODNAME VARCHAR2(50),
    PRODTYPE VARCHAR2(20),
    AVAILABLE_QUANTITY INT
);

-- 3: Create a table for Supplies with foreign key constraints
CREATE TABLE SUPPLIES (
    SUPNR INT NOT NULL,
    PRODNR NUMBER(3) NOT NULL,
    PURCHASE_PRICE NUMBER(10, 2),
    DELIV_PERIOD_DAYS NUMBER(3),
    PRIMARY KEY (SUPNR, PRODNR),
    CONSTRAINT FK_SUPPLIES_SUPPLIER FOREIGN KEY (SUPNR) REFERENCES SUPPLIER(SUPNR),
    CONSTRAINT FK_SUPPLIES_PRODUCT FOREIGN KEY (PRODNR) REFERENCES PRODUCT(PRODNR)
);

-- 4: Create a table for Purchase Order with foreign key constraints
CREATE TABLE PURCHASE_ORDER (
    PONR INT NOT NULL PRIMARY KEY,
    PODATE DATE,
    QUANTITY INT,
    PRODNR NUMBER(3) NOT NULL,
    SUPNR INT NOT NULL,
    CONSTRAINT FK_PURCHASE_ORDER_SUPPLIER FOREIGN KEY (SUPNR) REFERENCES SUPPLIER(SUPNR),
    CONSTRAINT FK_PURCHASE_ORDER_PRODUCT FOREIGN KEY (PRODNR) REFERENCES PRODUCT(PRODNR)
);

-- 5: Create a table for Customer
CREATE TABLE CUSTOMER (
    CUSTOMER_ID INT NOT NULL PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(30),
    EMAIL VARCHAR(30),
    ADDRESS VARCHAR(50)
);

-- 6: Show constraints for the PRODUCT table
SELECT *
FROM user_cons_columns
WHERE table_name = 'PRODUCT';

-- 7: Perform ALTER TABLE operations on the CUSTOMER table
-- A) Modify the CUSTOMER_ID column data type
ALTER TABLE CUSTOMER
MODIFY CUSTOMER_ID NUMBER(4);

-- B) Add a new column QUALIFICATION
ALTER TABLE CUSTOMER
ADD QUALIFICATION VARCHAR(30);

-- C) Drop the column QUALIFICATION
ALTER TABLE CUSTOMER
DROP COLUMN QUALIFICATION;

-- D) Add a unique constraint on the EMAIL column
ALTER TABLE CUSTOMER
ADD CONSTRAINT UNIQUE_EMAIL UNIQUE(EMAIL);

-- E) Drop the unique constraint on the EMAIL column
ALTER TABLE CUSTOMER
DROP CONSTRAINT UNIQUE_EMAIL;

-- F) Add a check constraint to verify the format of the EMAIL column
ALTER TABLE CUSTOMER
ADD CONSTRAINT VERIFY_EMAIL CHECK(EMAIL LIKE '%@%');

-- 8: Insert data into the CUSTOMER table
INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, EMAIL, ADDRESS)
VALUES (2, 'Ahmed ALI', 'aali@iba.edu.pk', 'Lahore');
